dist: trusty
sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
php:
- 7.2
- 7.3
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
- npm run lint
before_deploy:
- npm run zip
- ls -la snow-monkey-editor.zip
- export RELEASE_FILE=$(ls snow-monkey-editor.zip)
deploy:
  provider: releases
  api_key:
    secure: jFfjsMxUovJM5Y9P9IqbpVCIiErL4PjOyJkKd5KRlM0YRdMCzvr7DbFly5ui+VFZUvYedIJIdCRckkxWHhITu74hxpKAyk/P1rxnjX4N2UFsIj+5JPKGWv9wsMEfQi5ZklGUxNLexDfzPwi//qbEDL+YwgQ8xOoWCKxHdxmzORyY0pdfglprof3kALHc2jsjkYAeKZgTGHaGLpv1jhz6nT+lWEdgguyl7CE8ZuPgO2M9j5+gHiIIadIQ/qgr2zZ1ke8ZV6+hmjuH4ypPV8yiaT/GUQPLC12oUALHYqRn8Ewh4pUb/B/X2ZaO+gJdVJ6/gKvyHym7HMKhVXOqCZHSXXX7zfw5sFBynWzGKtXzt4VlIUdtFD6n1N4/0anl2368d/l0jImyTchIBk6+SOFb0JnZnMNXW6qeCBAFQ8vWb0cqSznTrAMZx0RiXbWDjhMeGUnALfjIb+8jCCbj/7oioKyEx/uhIiJbcg3LY+bJnJgl8wd/5cnHQvNxGSoDR8u+pvxrTtxcPwjG/5CZ88uqHN7pRVrMKfdGtZHGefoERnS4CSKUOvKJunw2QXhQR1Mp8JtH9KrN0NObqnE2a+GEisrAVgwee+xkoT1ydfrid78JK5gSqMOpIrX0nX0N7BhzUJVn4R9SfbB8jt7SqT1NYdwlnAjNmzHMC7nN8yEZ0ig=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.3
    repo: inc2734/snow-monkey-editor
